/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as VasRouteImport } from './routes/vas'
import { Route as SlottingRouteImport } from './routes/slotting'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as PalletsRouteImport } from './routes/pallets'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EdiRouteImport } from './routes/edi'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CrossdockRouteImport } from './routes/crossdock'
import { Route as CountingRouteImport } from './routes/counting'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CatchWeightRouteImport } from './routes/catch-weight'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as Allocation_backupRouteImport } from './routes/allocation_backup'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantPortalIndexRouteImport } from './routes/tenant-portal/index'
import { Route as RmaIndexRouteImport } from './routes/rma/index'
import { Route as RfIndexRouteImport } from './routes/rf/index'
import { Route as RateShoppingIndexRouteImport } from './routes/rate-shopping/index'
import { Route as WorkforceForecastRouteImport } from './routes/workforce/forecast'
import { Route as RfReceivingRouteImport } from './routes/rf/receiving'
import { Route as RfPutawayRouteImport } from './routes/rf/putaway'
import { Route as RfPickRouteImport } from './routes/rf/pick'
import { Route as RfMoveRouteImport } from './routes/rf/move'
import { Route as RfInquiryRouteImport } from './routes/rf/inquiry'
import { Route as RfHistoryRouteImport } from './routes/rf/history'
import { Route as MastersWarehousesRouteImport } from './routes/masters/warehouses'
import { Route as MastersEmployeesRouteImport } from './routes/masters/employees'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const VasRoute = VasRouteImport.update({
  id: '/vas',
  path: '/vas',
  getParentRoute: () => rootRouteImport,
} as any)
const SlottingRoute = SlottingRouteImport.update({
  id: '/slotting',
  path: '/slotting',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletsRoute = PalletsRouteImport.update({
  id: '/pallets',
  path: '/pallets',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EdiRoute = EdiRouteImport.update({
  id: '/edi',
  path: '/edi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossdockRoute = CrossdockRouteImport.update({
  id: '/crossdock',
  path: '/crossdock',
  getParentRoute: () => rootRouteImport,
} as any)
const CountingRoute = CountingRouteImport.update({
  id: '/counting',
  path: '/counting',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchWeightRoute = CatchWeightRouteImport.update({
  id: '/catch-weight',
  path: '/catch-weight',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const Allocation_backupRoute = Allocation_backupRouteImport.update({
  id: '/allocation_backup',
  path: '/allocation_backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPortalIndexRoute = TenantPortalIndexRouteImport.update({
  id: '/tenant-portal/',
  path: '/tenant-portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const RmaIndexRoute = RmaIndexRouteImport.update({
  id: '/rma/',
  path: '/rma/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfIndexRoute = RfIndexRouteImport.update({
  id: '/rf/',
  path: '/rf/',
  getParentRoute: () => rootRouteImport,
} as any)
const RateShoppingIndexRoute = RateShoppingIndexRouteImport.update({
  id: '/rate-shopping/',
  path: '/rate-shopping/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceForecastRoute = WorkforceForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => WorkforceRoute,
} as any)
const RfReceivingRoute = RfReceivingRouteImport.update({
  id: '/rf/receiving',
  path: '/rf/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const RfPutawayRoute = RfPutawayRouteImport.update({
  id: '/rf/putaway',
  path: '/rf/putaway',
  getParentRoute: () => rootRouteImport,
} as any)
const RfPickRoute = RfPickRouteImport.update({
  id: '/rf/pick',
  path: '/rf/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const RfMoveRoute = RfMoveRouteImport.update({
  id: '/rf/move',
  path: '/rf/move',
  getParentRoute: () => rootRouteImport,
} as any)
const RfInquiryRoute = RfInquiryRouteImport.update({
  id: '/rf/inquiry',
  path: '/rf/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const RfHistoryRoute = RfHistoryRouteImport.update({
  id: '/rf/history',
  path: '/rf/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersWarehousesRoute = MastersWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => MastersRoute,
} as any)
const MastersEmployeesRoute = MastersEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MastersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/allocation_backup': typeof Allocation_backupRoute
  '/billing': typeof BillingRoute
  '/catch-weight': typeof CatchWeightRoute
  '/compliance': typeof ComplianceRoute
  '/counting': typeof CountingRoute
  '/crossdock': typeof CrossdockRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/health': typeof HealthRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRouteWithChildren
  '/orders': typeof OrdersRoute
  '/packing': typeof PackingRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/slotting': typeof SlottingRoute
  '/vas': typeof VasRoute
  '/workforce': typeof WorkforceRouteWithChildren
  '/masters/employees': typeof MastersEmployeesRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/rf/history': typeof RfHistoryRoute
  '/rf/inquiry': typeof RfInquiryRoute
  '/rf/move': typeof RfMoveRoute
  '/rf/pick': typeof RfPickRoute
  '/rf/putaway': typeof RfPutawayRoute
  '/rf/receiving': typeof RfReceivingRoute
  '/workforce/forecast': typeof WorkforceForecastRoute
  '/rate-shopping/': typeof RateShoppingIndexRoute
  '/rf/': typeof RfIndexRoute
  '/rma/': typeof RmaIndexRoute
  '/tenant-portal/': typeof TenantPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/allocation_backup': typeof Allocation_backupRoute
  '/billing': typeof BillingRoute
  '/catch-weight': typeof CatchWeightRoute
  '/compliance': typeof ComplianceRoute
  '/counting': typeof CountingRoute
  '/crossdock': typeof CrossdockRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/health': typeof HealthRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRouteWithChildren
  '/orders': typeof OrdersRoute
  '/packing': typeof PackingRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/slotting': typeof SlottingRoute
  '/vas': typeof VasRoute
  '/workforce': typeof WorkforceRouteWithChildren
  '/masters/employees': typeof MastersEmployeesRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/rf/history': typeof RfHistoryRoute
  '/rf/inquiry': typeof RfInquiryRoute
  '/rf/move': typeof RfMoveRoute
  '/rf/pick': typeof RfPickRoute
  '/rf/putaway': typeof RfPutawayRoute
  '/rf/receiving': typeof RfReceivingRoute
  '/workforce/forecast': typeof WorkforceForecastRoute
  '/rate-shopping': typeof RateShoppingIndexRoute
  '/rf': typeof RfIndexRoute
  '/rma': typeof RmaIndexRoute
  '/tenant-portal': typeof TenantPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/allocation_backup': typeof Allocation_backupRoute
  '/billing': typeof BillingRoute
  '/catch-weight': typeof CatchWeightRoute
  '/compliance': typeof ComplianceRoute
  '/counting': typeof CountingRoute
  '/crossdock': typeof CrossdockRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/health': typeof HealthRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRouteWithChildren
  '/orders': typeof OrdersRoute
  '/packing': typeof PackingRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/slotting': typeof SlottingRoute
  '/vas': typeof VasRoute
  '/workforce': typeof WorkforceRouteWithChildren
  '/masters/employees': typeof MastersEmployeesRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/rf/history': typeof RfHistoryRoute
  '/rf/inquiry': typeof RfInquiryRoute
  '/rf/move': typeof RfMoveRoute
  '/rf/pick': typeof RfPickRoute
  '/rf/putaway': typeof RfPutawayRoute
  '/rf/receiving': typeof RfReceivingRoute
  '/workforce/forecast': typeof WorkforceForecastRoute
  '/rate-shopping/': typeof RateShoppingIndexRoute
  '/rf/': typeof RfIndexRoute
  '/rma/': typeof RmaIndexRoute
  '/tenant-portal/': typeof TenantPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/allocation_backup'
    | '/billing'
    | '/catch-weight'
    | '/compliance'
    | '/counting'
    | '/crossdock'
    | '/documents'
    | '/edi'
    | '/health'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/orders'
    | '/packing'
    | '/pallets'
    | '/picks'
    | '/scoreboard'
    | '/settings'
    | '/shipments'
    | '/slotting'
    | '/vas'
    | '/workforce'
    | '/masters/employees'
    | '/masters/warehouses'
    | '/rf/history'
    | '/rf/inquiry'
    | '/rf/move'
    | '/rf/pick'
    | '/rf/putaway'
    | '/rf/receiving'
    | '/workforce/forecast'
    | '/rate-shopping/'
    | '/rf/'
    | '/rma/'
    | '/tenant-portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/allocation_backup'
    | '/billing'
    | '/catch-weight'
    | '/compliance'
    | '/counting'
    | '/crossdock'
    | '/documents'
    | '/edi'
    | '/health'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/orders'
    | '/packing'
    | '/pallets'
    | '/picks'
    | '/scoreboard'
    | '/settings'
    | '/shipments'
    | '/slotting'
    | '/vas'
    | '/workforce'
    | '/masters/employees'
    | '/masters/warehouses'
    | '/rf/history'
    | '/rf/inquiry'
    | '/rf/move'
    | '/rf/pick'
    | '/rf/putaway'
    | '/rf/receiving'
    | '/workforce/forecast'
    | '/rate-shopping'
    | '/rf'
    | '/rma'
    | '/tenant-portal'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/allocation_backup'
    | '/billing'
    | '/catch-weight'
    | '/compliance'
    | '/counting'
    | '/crossdock'
    | '/documents'
    | '/edi'
    | '/health'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/orders'
    | '/packing'
    | '/pallets'
    | '/picks'
    | '/scoreboard'
    | '/settings'
    | '/shipments'
    | '/slotting'
    | '/vas'
    | '/workforce'
    | '/masters/employees'
    | '/masters/warehouses'
    | '/rf/history'
    | '/rf/inquiry'
    | '/rf/move'
    | '/rf/pick'
    | '/rf/putaway'
    | '/rf/receiving'
    | '/workforce/forecast'
    | '/rate-shopping/'
    | '/rf/'
    | '/rma/'
    | '/tenant-portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  Allocation_backupRoute: typeof Allocation_backupRoute
  BillingRoute: typeof BillingRoute
  CatchWeightRoute: typeof CatchWeightRoute
  ComplianceRoute: typeof ComplianceRoute
  CountingRoute: typeof CountingRoute
  CrossdockRoute: typeof CrossdockRoute
  DocumentsRoute: typeof DocumentsRoute
  EdiRoute: typeof EdiRoute
  HealthRoute: typeof HealthRoute
  InboundRoute: typeof InboundRoute
  InventoryRoute: typeof InventoryRoute
  MastersRoute: typeof MastersRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  PackingRoute: typeof PackingRoute
  PalletsRoute: typeof PalletsRoute
  PicksRoute: typeof PicksRoute
  ScoreboardRoute: typeof ScoreboardRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SlottingRoute: typeof SlottingRoute
  VasRoute: typeof VasRoute
  WorkforceRoute: typeof WorkforceRouteWithChildren
  RfHistoryRoute: typeof RfHistoryRoute
  RfInquiryRoute: typeof RfInquiryRoute
  RfMoveRoute: typeof RfMoveRoute
  RfPickRoute: typeof RfPickRoute
  RfPutawayRoute: typeof RfPutawayRoute
  RfReceivingRoute: typeof RfReceivingRoute
  RateShoppingIndexRoute: typeof RateShoppingIndexRoute
  RfIndexRoute: typeof RfIndexRoute
  RmaIndexRoute: typeof RmaIndexRoute
  TenantPortalIndexRoute: typeof TenantPortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vas': {
      id: '/vas'
      path: '/vas'
      fullPath: '/vas'
      preLoaderRoute: typeof VasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slotting': {
      id: '/slotting'
      path: '/slotting'
      fullPath: '/slotting'
      preLoaderRoute: typeof SlottingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallets': {
      id: '/pallets'
      path: '/pallets'
      fullPath: '/pallets'
      preLoaderRoute: typeof PalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edi': {
      id: '/edi'
      path: '/edi'
      fullPath: '/edi'
      preLoaderRoute: typeof EdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crossdock': {
      id: '/crossdock'
      path: '/crossdock'
      fullPath: '/crossdock'
      preLoaderRoute: typeof CrossdockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counting': {
      id: '/counting'
      path: '/counting'
      fullPath: '/counting'
      preLoaderRoute: typeof CountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catch-weight': {
      id: '/catch-weight'
      path: '/catch-weight'
      fullPath: '/catch-weight'
      preLoaderRoute: typeof CatchWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation_backup': {
      id: '/allocation_backup'
      path: '/allocation_backup'
      fullPath: '/allocation_backup'
      preLoaderRoute: typeof Allocation_backupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-portal/': {
      id: '/tenant-portal/'
      path: '/tenant-portal'
      fullPath: '/tenant-portal/'
      preLoaderRoute: typeof TenantPortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rma/': {
      id: '/rma/'
      path: '/rma'
      fullPath: '/rma/'
      preLoaderRoute: typeof RmaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/': {
      id: '/rf/'
      path: '/rf'
      fullPath: '/rf/'
      preLoaderRoute: typeof RfIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-shopping/': {
      id: '/rate-shopping/'
      path: '/rate-shopping'
      fullPath: '/rate-shopping/'
      preLoaderRoute: typeof RateShoppingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/forecast': {
      id: '/workforce/forecast'
      path: '/forecast'
      fullPath: '/workforce/forecast'
      preLoaderRoute: typeof WorkforceForecastRouteImport
      parentRoute: typeof WorkforceRoute
    }
    '/rf/receiving': {
      id: '/rf/receiving'
      path: '/rf/receiving'
      fullPath: '/rf/receiving'
      preLoaderRoute: typeof RfReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/putaway': {
      id: '/rf/putaway'
      path: '/rf/putaway'
      fullPath: '/rf/putaway'
      preLoaderRoute: typeof RfPutawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/pick': {
      id: '/rf/pick'
      path: '/rf/pick'
      fullPath: '/rf/pick'
      preLoaderRoute: typeof RfPickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/move': {
      id: '/rf/move'
      path: '/rf/move'
      fullPath: '/rf/move'
      preLoaderRoute: typeof RfMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/inquiry': {
      id: '/rf/inquiry'
      path: '/rf/inquiry'
      fullPath: '/rf/inquiry'
      preLoaderRoute: typeof RfInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/history': {
      id: '/rf/history'
      path: '/rf/history'
      fullPath: '/rf/history'
      preLoaderRoute: typeof RfHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/warehouses': {
      id: '/masters/warehouses'
      path: '/warehouses'
      fullPath: '/masters/warehouses'
      preLoaderRoute: typeof MastersWarehousesRouteImport
      parentRoute: typeof MastersRoute
    }
    '/masters/employees': {
      id: '/masters/employees'
      path: '/employees'
      fullPath: '/masters/employees'
      preLoaderRoute: typeof MastersEmployeesRouteImport
      parentRoute: typeof MastersRoute
    }
  }
}

interface MastersRouteChildren {
  MastersEmployeesRoute: typeof MastersEmployeesRoute
  MastersWarehousesRoute: typeof MastersWarehousesRoute
}

const MastersRouteChildren: MastersRouteChildren = {
  MastersEmployeesRoute: MastersEmployeesRoute,
  MastersWarehousesRoute: MastersWarehousesRoute,
}

const MastersRouteWithChildren =
  MastersRoute._addFileChildren(MastersRouteChildren)

interface WorkforceRouteChildren {
  WorkforceForecastRoute: typeof WorkforceForecastRoute
}

const WorkforceRouteChildren: WorkforceRouteChildren = {
  WorkforceForecastRoute: WorkforceForecastRoute,
}

const WorkforceRouteWithChildren = WorkforceRoute._addFileChildren(
  WorkforceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  Allocation_backupRoute: Allocation_backupRoute,
  BillingRoute: BillingRoute,
  CatchWeightRoute: CatchWeightRoute,
  ComplianceRoute: ComplianceRoute,
  CountingRoute: CountingRoute,
  CrossdockRoute: CrossdockRoute,
  DocumentsRoute: DocumentsRoute,
  EdiRoute: EdiRoute,
  HealthRoute: HealthRoute,
  InboundRoute: InboundRoute,
  InventoryRoute: InventoryRoute,
  MastersRoute: MastersRouteWithChildren,
  OrdersRoute: OrdersRoute,
  PackingRoute: PackingRoute,
  PalletsRoute: PalletsRoute,
  PicksRoute: PicksRoute,
  ScoreboardRoute: ScoreboardRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SlottingRoute: SlottingRoute,
  VasRoute: VasRoute,
  WorkforceRoute: WorkforceRouteWithChildren,
  RfHistoryRoute: RfHistoryRoute,
  RfInquiryRoute: RfInquiryRoute,
  RfMoveRoute: RfMoveRoute,
  RfPickRoute: RfPickRoute,
  RfPutawayRoute: RfPutawayRoute,
  RfReceivingRoute: RfReceivingRoute,
  RateShoppingIndexRoute: RateShoppingIndexRoute,
  RfIndexRoute: RfIndexRoute,
  RmaIndexRoute: RmaIndexRoute,
  TenantPortalIndexRoute: TenantPortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
