/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as PalletsRouteImport } from './routes/pallets'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as EdiRouteImport } from './routes/edi'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as IndexRouteImport } from './routes/index'

const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletsRoute = PalletsRouteImport.update({
  id: '/pallets',
  path: '/pallets',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const EdiRoute = EdiRouteImport.update({
  id: '/edi',
  path: '/edi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/billing': typeof BillingRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRoute
  '/orders': typeof OrdersRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/billing': typeof BillingRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRoute
  '/orders': typeof OrdersRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/billing': typeof BillingRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRoute
  '/orders': typeof OrdersRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/billing'
    | '/documents'
    | '/edi'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/orders'
    | '/pallets'
    | '/picks'
    | '/settings'
    | '/shipments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/billing'
    | '/documents'
    | '/edi'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/orders'
    | '/pallets'
    | '/picks'
    | '/settings'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/billing'
    | '/documents'
    | '/edi'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/orders'
    | '/pallets'
    | '/picks'
    | '/settings'
    | '/shipments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  BillingRoute: typeof BillingRoute
  DocumentsRoute: typeof DocumentsRoute
  EdiRoute: typeof EdiRoute
  InboundRoute: typeof InboundRoute
  InventoryRoute: typeof InventoryRoute
  MastersRoute: typeof MastersRoute
  OrdersRoute: typeof OrdersRoute
  PalletsRoute: typeof PalletsRoute
  PicksRoute: typeof PicksRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallets': {
      id: '/pallets'
      path: '/pallets'
      fullPath: '/pallets'
      preLoaderRoute: typeof PalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edi': {
      id: '/edi'
      path: '/edi'
      fullPath: '/edi'
      preLoaderRoute: typeof EdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  BillingRoute: BillingRoute,
  DocumentsRoute: DocumentsRoute,
  EdiRoute: EdiRoute,
  InboundRoute: InboundRoute,
  InventoryRoute: InventoryRoute,
  MastersRoute: MastersRoute,
  OrdersRoute: OrdersRoute,
  PalletsRoute: PalletsRoute,
  PicksRoute: PicksRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
