/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as PalletsRouteImport } from './routes/pallets'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as WarehousesRouteImport } from './routes/masters/warehouses'
import { Route as EmployeesRouteImport } from './routes/masters/employees'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as EdiRouteImport } from './routes/edi'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as Allocation_backupRouteImport } from './routes/allocation_backup'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RfRouteImport } from './routes/rf/index'
import { Route as RfPutawayRouteImport } from './routes/rf/putaway'
import { Route as RfMoveRouteImport } from './routes/rf/move'
import { Route as RfPickRouteImport } from './routes/rf/pick'
import { Route as RfReceivingRouteImport } from './routes/rf/receiving'
import { Route as RfInquiryRouteImport } from './routes/rf/inquiry'
import { Route as RfHistoryRouteImport } from './routes/rf/history'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as SlottingRouteImport } from './routes/slotting'
import { Route as ComplianceRouteImport } from './routes/compliance'

const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const PalletsRoute = PalletsRouteImport.update({
  id: '/pallets',
  path: '/pallets',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const EdiRoute = EdiRouteImport.update({
  id: '/edi',
  path: '/edi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const Allocation_backupRoute = Allocation_backupRouteImport.update({
  id: '/allocation_backup',
  path: '/allocation_backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfRoute = RfRouteImport.update({
  id: '/rf',
  path: '/rf',
  getParentRoute: () => rootRouteImport,
} as any)
const RfPutawayRoute = RfPutawayRouteImport.update({
  id: '/rf/putaway',
  path: '/rf/putaway',
  getParentRoute: () => RfRoute,
} as any)
const RfMoveRoute = RfMoveRouteImport.update({
  id: '/rf/move',
  path: '/rf/move',
  getParentRoute: () => RfRoute,
} as any)
const RfPickRoute = RfPickRouteImport.update({
  id: '/rf/pick',
  path: '/rf/pick',
  getParentRoute: () => RfRoute,
} as any)
const RfReceivingRoute = RfReceivingRouteImport.update({
  id: '/rf/receiving',
  path: '/rf/receiving',
  getParentRoute: () => RfRoute,
} as any)
const RfInquiryRoute = RfInquiryRouteImport.update({
  id: '/rf/inquiry',
  path: '/rf/inquiry',
  getParentRoute: () => RfRoute,
} as any)
const RfHistoryRoute = RfHistoryRouteImport.update({
  id: '/rf/history',
  path: '/rf/history',
  getParentRoute: () => RfRoute,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/masters/warehouses',
  path: '/masters/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/masters/employees',
  path: '/masters/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlottingRoute = SlottingRouteImport.update({
  id: '/slotting',
  path: '/slotting',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/allocation_backup': typeof Allocation_backupRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRoute
  '/masters/warehouses': typeof WarehousesRoute
  '/masters/employees': typeof EmployeesRoute
  '/orders': typeof OrdersRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/rf/putaway': typeof RfPutawayRoute
  '/rf/move': typeof RfMoveRoute
  '/rf/pick': typeof RfPickRoute
  '/rf/receiving': typeof RfReceivingRoute
  '/rf/inquiry': typeof RfInquiryRoute
  '/rf/history': typeof RfHistoryRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/slotting': typeof SlottingRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/allocation_backup': typeof Allocation_backupRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRoute
  '/masters/warehouses': typeof WarehousesRoute
  '/masters/employees': typeof EmployeesRoute
  '/orders': typeof OrdersRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/rf': typeof RfRoute
  '/rf/putaway': typeof RfPutawayRoute
  '/rf/move': typeof RfMoveRoute
  '/rf/pick': typeof RfPickRoute
  '/rf/receiving': typeof RfReceivingRoute
  '/rf/inquiry': typeof RfInquiryRoute
  '/rf/history': typeof RfHistoryRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/slotting': typeof SlottingRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/allocation_backup': typeof Allocation_backupRoute
  '/billing': typeof BillingRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/edi': typeof EdiRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/masters': typeof MastersRoute
  '/masters/warehouses': typeof WarehousesRoute
  '/masters/employees': typeof EmployeesRoute
  '/orders': typeof OrdersRoute
  '/pallets': typeof PalletsRoute
  '/picks': typeof PicksRoute
  '/rf': typeof RfRoute
  '/rf/putaway': typeof RfPutawayRoute
  '/rf/move': typeof RfMoveRoute
  '/rf/pick': typeof RfPickRoute
  '/rf/receiving': typeof RfReceivingRoute
  '/rf/inquiry': typeof RfInquiryRoute
  '/rf/history': typeof RfHistoryRoute
  '/scoreboard': typeof ScoreboardRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/slotting': typeof SlottingRoute
  '/workforce': typeof WorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/allocation_backup'
    | '/billing'
    | '/compliance'
    | '/documents'
    | '/edi'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/masters/warehouses'
    | '/masters/employees'
    | '/orders'
    | '/pallets'
    | '/picks'
    | '/rf'
    | '/rf/putaway'
    | '/rf/move'
    | '/rf/pick'
    | '/rf/receiving'
    | '/rf/inquiry'
    | '/rf/history'
    | '/scoreboard'
    | '/settings'
    | '/shipments'
    | '/slotting'
    | '/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/allocation_backup'
    | '/billing'
    | '/compliance'
    | '/documents'
    | '/edi'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/masters/warehouses'
    | '/masters/employees'
    | '/orders'
    | '/pallets'
    | '/picks'
    | '/rf'
    | '/rf/putaway'
    | '/rf/move'
    | '/rf/pick'
    | '/rf/receiving'
    | '/rf/inquiry'
    | '/rf/history'
    | '/scoreboard'
    | '/settings'
    | '/shipments'
    | '/slotting'
    | '/workforce'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/allocation_backup'
    | '/billing'
    | '/compliance'
    | '/documents'
    | '/edi'
    | '/inbound'
    | '/inventory'
    | '/masters'
    | '/masters/warehouses'
    | '/masters/employees'
    | '/orders'
    | '/pallets'
    | '/picks'
    | '/rf'
    | '/rf/putaway'
    | '/rf/move'
    | '/rf/pick'
    | '/rf/receiving'
    | '/rf/inquiry'
    | '/rf/history'
    | '/scoreboard'
    | '/settings'
    | '/shipments'
    | '/slotting'
    | '/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  Allocation_backupRoute: typeof Allocation_backupRoute
  BillingRoute: typeof BillingRoute
  ComplianceRoute: typeof ComplianceRoute
  DocumentsRoute: typeof DocumentsRoute
  EdiRoute: typeof EdiRoute
  InboundRoute: typeof InboundRoute
  InventoryRoute: typeof InventoryRoute
  MastersRoute: typeof MastersRoute
  WarehousesRoute: typeof WarehousesRoute
  EmployeesRoute: typeof EmployeesRoute
  OrdersRoute: typeof OrdersRoute
  PalletsRoute: typeof PalletsRoute
  PicksRoute: typeof PicksRoute
  RfRoute: typeof RfRoute
  RfPutawayRoute: typeof RfPutawayRoute
  RfMoveRoute: typeof RfMoveRoute
  RfPickRoute: typeof RfPickRoute
  RfReceivingRoute: typeof RfReceivingRoute
  RfInquiryRoute: typeof RfInquiryRoute
  RfHistoryRoute: typeof RfHistoryRoute
  ScoreboardRoute: typeof ScoreboardRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SlottingRoute: typeof SlottingRoute
  WorkforceRoute: typeof WorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slotting': {
      id: '/slotting'
      path: '/slotting'
      fullPath: '/slotting'
      preLoaderRoute: typeof SlottingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf/history': {
      id: '/rf/history'
      path: '/rf/history'
      fullPath: '/rf/history'
      preLoaderRoute: typeof RfHistoryRouteImport
      parentRoute: typeof RfRouteImport
    }
    '/rf/inquiry': {
      id: '/rf/inquiry'
      path: '/rf/inquiry'
      fullPath: '/rf/inquiry'
      preLoaderRoute: typeof RfInquiryRouteImport
      parentRoute: typeof RfRouteImport
    }
    '/rf/receiving': {
      id: '/rf/receiving'
      path: '/rf/receiving'
      fullPath: '/rf/receiving'
      preLoaderRoute: typeof RfReceivingRouteImport
      parentRoute: typeof RfRouteImport
    }
    '/rf/pick': {
      id: '/rf/pick'
      path: '/rf/pick'
      fullPath: '/rf/pick'
      preLoaderRoute: typeof RfPickRouteImport
      parentRoute: typeof RfRouteImport
    }
    '/rf/move': {
      id: '/rf/move'
      path: '/rf/move'
      fullPath: '/rf/move'
      preLoaderRoute: typeof RfMoveRouteImport
      parentRoute: typeof RfRouteImport
    }
    '/rf/putaway': {
      id: '/rf/putaway'
      path: '/rf/putaway'
      fullPath: '/rf/putaway'
      preLoaderRoute: typeof RfPutawayRouteImport
      parentRoute: typeof RfRouteImport
    }
    '/rf': {
      id: '/rf'
      path: '/rf'
      fullPath: '/rf'
      preLoaderRoute: typeof RfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pallets': {
      id: '/pallets'
      path: '/pallets'
      fullPath: '/pallets'
      preLoaderRoute: typeof PalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/employees': {
      id: '/masters/employees'
      path: '/masters/employees'
      fullPath: '/masters/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/warehouses': {
      id: '/masters/warehouses'
      path: '/masters/warehouses'
      fullPath: '/masters/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edi': {
      id: '/edi'
      path: '/edi'
      fullPath: '/edi'
      preLoaderRoute: typeof EdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation_backup': {
      id: '/allocation_backup'
      path: '/allocation_backup'
      fullPath: '/allocation_backup'
      preLoaderRoute: typeof Allocation_backupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  Allocation_backupRoute: Allocation_backupRoute,
  BillingRoute: BillingRoute,
  ComplianceRoute: ComplianceRoute,
  DocumentsRoute: DocumentsRoute,
  EdiRoute: EdiRoute,
  InboundRoute: InboundRoute,
  InventoryRoute: InventoryRoute,
  MastersRoute: MastersRoute,
  WarehousesRoute: WarehousesRoute,
  EmployeesRoute: EmployeesRoute,
  OrdersRoute: OrdersRoute,
  PalletsRoute: PalletsRoute,
  PicksRoute: PicksRoute,
  RfRoute: RfRoute,
  RfPutawayRoute: RfPutawayRoute,
  RfMoveRoute: RfMoveRoute,
  RfPickRoute: RfPickRoute,
  RfReceivingRoute: RfReceivingRoute,
  RfInquiryRoute: RfInquiryRoute,
  RfHistoryRoute: RfHistoryRoute,
  ScoreboardRoute: ScoreboardRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SlottingRoute: SlottingRoute,
  WorkforceRoute: WorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
